### ISSUE TITLE
1.9.8 Breaks Slack Notifications

### ISSUE THREAD

**Issue by nickkeenan** [yehudah/Post-SMTP#54]
This is a cross post of this ongoing issue on WordPress.org: 

https://wordpress.org/support/topic/call-to-undefined-method-postmanoptionsgetslacktoken/

Since 1.9.8 at least, when the Slack Notification feature is enabled, this triggers a fatal error when SMTP fails and the plugin attempts to notify Slack: 

An error of type E_ERROR was caused in line 11 of the file /home4/airrudd/public_html/wp-content/plugins/post-smtp/Postman/Extensions/Core/Notifications/PostmanSlackNotify.php. Error message: Uncaught Error: **Call to undefined method PostmanOptions::getSlackToken()** in /home4/airrudd/public_html/wp-content/plugins/post-smtp/Postman/Extensions/Core/Notifications/PostmanSlackNotify.php:11
Stack trace:
#0 /home4/airrudd/public_html/wp-content/plugins/post-smtp/Postman/Extensions/Core/Notifications/PostmanNotify.php(209): PostmanSlackNotify->send_message(‘You getting thi…’, Object(PostmanEmailLog))
#1 /home4/airrudd/public_html/wp-includes/class-wp-hook.php(288): PostmanNotify->notify(Object(PostmanEmailLog), Object(PostmanMessage), ‘220-cloud189.ho…’, Object(PostmanSmtpModuleTransport), ‘No recipient fo…’)
#2 /home4/airrudd/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(”, Array)
#3 /home4/airrudd/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home4/airrudd/public_html/wp-content/plugins/post-smtp/Postman/PostmanWpMail.php(276): do_action(‘post_smtp_on_fa…’, Object(PostmanEmailLog), Object(PostmanMessage), ‘220-cloud189.ho…’, Object(PostmanSmtp)

**Comment by nickkeenan** [comment]
Issue is fixed in v. 2.0.11
